version: '3'

services:
  linebot:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./docs:/app/docs
    env_file:
      - .env
    restart: always

  ngrok:
    image: ngrok/ngrok:latest
    command: "http linebot:5000"
    depends_on:
      - linebot
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}